name: PR checks
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  PR-Checks:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 7.12.1
      - name: Setup nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.0'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - run: npm run prettier
      - run: npm run lint
      - run: npm run tsc
      - run: npm run test
